{% set name = "gemmi" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 58ed9023e0f75033ebec1da630461bc6e1af661f29f0c41deed66c20315ebe2a

build:
  number: 2
  run_exports: {{ pin_subpackage(name, max_pin="x.x.x") }}
  script:
    - {{ PYTHON }} -m pip install . -vv --config-settings="cmake.args=-DBUILD_GEMMI_PROGRAM=ON;-DUSE_ZLIB_NG=ON"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - python
    - nanobind
    - scikit-build-core
    - pip
    - zlib-ng
  run:
    - python

test:
  source_files:
    - tests
    - examples
  commands:
    - gemmi --help
    - pip check
    - python -m unittest discover -s tests -v
  imports:
    - gemmi
  requires:
    - pip
    - numpy

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Macromolecular crystallography library and utilities.
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - ndevenish
    - wojdyr
    - mcs07
